baseURL = "/"
languageCode = "en-us"
title = "SourceBans++"
theme = "kube"
Paginate = 4
googleAnalytics = "UA-68577666-5"
enableGitInfo = true
enableEmoji = true

[Params]
  description = "Global admin, ban, and communication management system for the Source engine"
  RSSLink = "/index.xml"
  author = "SourceBans++"
  github = "sbpp"
  discord = "4Bhj6NU"

[Params.seo.webmaster_verifications]
  google = "NMu_qHiZPOvLzW1_DvAKrQfdQUAOdKxGnjbI8oa0cGo"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = -100
    url = "/faq/"
[[menu.main]]
    name = " Discord"
    pre = "<i class='fab fa-discord' data-fa-transform='down-1' style='color:#7289DA'></i>"
    weight = -99
    url = "https://discord.gg/4Bhj6NU"
